{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMJavLuIqgirbNfVtKJy2RP",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bish-ai/bish_multi_disease_classifier/blob/main/multi_disease_classsifier.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 73
        },
        "id": "59195DCGvu1C",
        "outputId": "96b86827-48c4-4e97-cf55-08b2fbf70b4b"
      },
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-ce280397-f2cf-4be8-bcfe-e2e3b987132d\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-ce280397-f2cf-4be8-bcfe-e2e3b987132d\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving Blood_samples_dataset_balanced_2(f).csv.zip to Blood_samples_dataset_balanced_2(f).csv (4).zip\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_b8a7dd6b-8e0f-497c-ab87-d96e9bc65303\", \"output.csv\", 1084153)"
            ]
          },
          "metadata": {}
        }
      ],
      "source": [
        "import pandas as pd\n",
        "from google.colab import files\n",
        "import zipfile, pandas as pd, os\n",
        "\n",
        "uploaded = files.upload()\n",
        "z = list(uploaded.keys())[0]\n",
        "\n",
        "with zipfile.ZipFile(z) as f:\n",
        "    f.extractall()\n",
        "\n",
        "csv_filename = [f for f in os.listdir() if f.endswith(\".csv\")][0]\n",
        "df = pd.read_csv(csv_filename)\n",
        "df.to_csv(\"output.csv\", index=False)\n",
        "\n",
        "files.download(\"output.csv\")"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 307
        },
        "id": "84c6cae3",
        "outputId": "0248702d-f39e-4460-e37b-6f5f8a5579a8"
      },
      "source": [
        "df = pd.read_csv('output.csv')\n",
        "df.head()"
      ],
      "execution_count": 34,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "    Glucose  Cholesterol  Hemoglobin  Platelets  White Blood Cells  \\\n",
              "0  0.739597     0.650198    0.713631   0.868491           0.687433   \n",
              "1  0.121786     0.023058    0.944893   0.905372           0.507711   \n",
              "2  0.452539     0.116135    0.544560   0.400640           0.294538   \n",
              "3  0.136609     0.015605    0.419957   0.191487           0.081168   \n",
              "4  0.176737     0.752220    0.971779   0.785286           0.443880   \n",
              "\n",
              "   Red Blood Cells  Hematocrit  Mean Corpuscular Volume  \\\n",
              "0         0.529895    0.290006                 0.631045   \n",
              "1         0.403033    0.164216                 0.307553   \n",
              "2         0.382021    0.625267                 0.295122   \n",
              "3         0.166214    0.073293                 0.668719   \n",
              "4         0.439851    0.894991                 0.442159   \n",
              "\n",
              "   Mean Corpuscular Hemoglobin  Mean Corpuscular Hemoglobin Concentration  \\\n",
              "0                     0.001328                                   0.795829   \n",
              "1                     0.207938                                   0.505562   \n",
              "2                     0.868369                                   0.026808   \n",
              "3                     0.125447                                   0.501051   \n",
              "4                     0.257288                                   0.805987   \n",
              "\n",
              "   ...     HbA1c  LDL Cholesterol  HDL Cholesterol       ALT       AST  \\\n",
              "0  ...  0.502665         0.215560         0.512941  0.064187  0.610827   \n",
              "1  ...  0.856810         0.652465         0.106961  0.942549  0.344261   \n",
              "2  ...  0.466795         0.387332         0.421763  0.007186  0.506918   \n",
              "3  ...  0.016256         0.040137         0.826721  0.265415  0.594148   \n",
              "4  ...  0.429431         0.146294         0.221574  0.015280  0.567115   \n",
              "\n",
              "   Heart Rate  Creatinine  Troponin  C-reactive Protein   Disease  \n",
              "0    0.939485    0.095512  0.465957            0.769230   Healthy  \n",
              "1    0.666368    0.659060  0.816982            0.401166  Diabetes  \n",
              "2    0.431704    0.417295  0.799074            0.779208  Thalasse  \n",
              "3    0.225756    0.490349  0.637061            0.354094    Anemia  \n",
              "4    0.841412    0.153350  0.794008            0.094970  Thalasse  \n",
              "\n",
              "[5 rows x 25 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-a27bda4a-50d1-4674-8de0-527ca411afda\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Glucose</th>\n",
              "      <th>Cholesterol</th>\n",
              "      <th>Hemoglobin</th>\n",
              "      <th>Platelets</th>\n",
              "      <th>White Blood Cells</th>\n",
              "      <th>Red Blood Cells</th>\n",
              "      <th>Hematocrit</th>\n",
              "      <th>Mean Corpuscular Volume</th>\n",
              "      <th>Mean Corpuscular Hemoglobin</th>\n",
              "      <th>Mean Corpuscular Hemoglobin Concentration</th>\n",
              "      <th>...</th>\n",
              "      <th>HbA1c</th>\n",
              "      <th>LDL Cholesterol</th>\n",
              "      <th>HDL Cholesterol</th>\n",
              "      <th>ALT</th>\n",
              "      <th>AST</th>\n",
              "      <th>Heart Rate</th>\n",
              "      <th>Creatinine</th>\n",
              "      <th>Troponin</th>\n",
              "      <th>C-reactive Protein</th>\n",
              "      <th>Disease</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0.739597</td>\n",
              "      <td>0.650198</td>\n",
              "      <td>0.713631</td>\n",
              "      <td>0.868491</td>\n",
              "      <td>0.687433</td>\n",
              "      <td>0.529895</td>\n",
              "      <td>0.290006</td>\n",
              "      <td>0.631045</td>\n",
              "      <td>0.001328</td>\n",
              "      <td>0.795829</td>\n",
              "      <td>...</td>\n",
              "      <td>0.502665</td>\n",
              "      <td>0.215560</td>\n",
              "      <td>0.512941</td>\n",
              "      <td>0.064187</td>\n",
              "      <td>0.610827</td>\n",
              "      <td>0.939485</td>\n",
              "      <td>0.095512</td>\n",
              "      <td>0.465957</td>\n",
              "      <td>0.769230</td>\n",
              "      <td>Healthy</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>0.121786</td>\n",
              "      <td>0.023058</td>\n",
              "      <td>0.944893</td>\n",
              "      <td>0.905372</td>\n",
              "      <td>0.507711</td>\n",
              "      <td>0.403033</td>\n",
              "      <td>0.164216</td>\n",
              "      <td>0.307553</td>\n",
              "      <td>0.207938</td>\n",
              "      <td>0.505562</td>\n",
              "      <td>...</td>\n",
              "      <td>0.856810</td>\n",
              "      <td>0.652465</td>\n",
              "      <td>0.106961</td>\n",
              "      <td>0.942549</td>\n",
              "      <td>0.344261</td>\n",
              "      <td>0.666368</td>\n",
              "      <td>0.659060</td>\n",
              "      <td>0.816982</td>\n",
              "      <td>0.401166</td>\n",
              "      <td>Diabetes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>0.452539</td>\n",
              "      <td>0.116135</td>\n",
              "      <td>0.544560</td>\n",
              "      <td>0.400640</td>\n",
              "      <td>0.294538</td>\n",
              "      <td>0.382021</td>\n",
              "      <td>0.625267</td>\n",
              "      <td>0.295122</td>\n",
              "      <td>0.868369</td>\n",
              "      <td>0.026808</td>\n",
              "      <td>...</td>\n",
              "      <td>0.466795</td>\n",
              "      <td>0.387332</td>\n",
              "      <td>0.421763</td>\n",
              "      <td>0.007186</td>\n",
              "      <td>0.506918</td>\n",
              "      <td>0.431704</td>\n",
              "      <td>0.417295</td>\n",
              "      <td>0.799074</td>\n",
              "      <td>0.779208</td>\n",
              "      <td>Thalasse</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>0.136609</td>\n",
              "      <td>0.015605</td>\n",
              "      <td>0.419957</td>\n",
              "      <td>0.191487</td>\n",
              "      <td>0.081168</td>\n",
              "      <td>0.166214</td>\n",
              "      <td>0.073293</td>\n",
              "      <td>0.668719</td>\n",
              "      <td>0.125447</td>\n",
              "      <td>0.501051</td>\n",
              "      <td>...</td>\n",
              "      <td>0.016256</td>\n",
              "      <td>0.040137</td>\n",
              "      <td>0.826721</td>\n",
              "      <td>0.265415</td>\n",
              "      <td>0.594148</td>\n",
              "      <td>0.225756</td>\n",
              "      <td>0.490349</td>\n",
              "      <td>0.637061</td>\n",
              "      <td>0.354094</td>\n",
              "      <td>Anemia</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>0.176737</td>\n",
              "      <td>0.752220</td>\n",
              "      <td>0.971779</td>\n",
              "      <td>0.785286</td>\n",
              "      <td>0.443880</td>\n",
              "      <td>0.439851</td>\n",
              "      <td>0.894991</td>\n",
              "      <td>0.442159</td>\n",
              "      <td>0.257288</td>\n",
              "      <td>0.805987</td>\n",
              "      <td>...</td>\n",
              "      <td>0.429431</td>\n",
              "      <td>0.146294</td>\n",
              "      <td>0.221574</td>\n",
              "      <td>0.015280</td>\n",
              "      <td>0.567115</td>\n",
              "      <td>0.841412</td>\n",
              "      <td>0.153350</td>\n",
              "      <td>0.794008</td>\n",
              "      <td>0.094970</td>\n",
              "      <td>Thalasse</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>5 rows × 25 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-a27bda4a-50d1-4674-8de0-527ca411afda')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-a27bda4a-50d1-4674-8de0-527ca411afda button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-a27bda4a-50d1-4674-8de0-527ca411afda');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df"
            }
          },
          "metadata": {},
          "execution_count": 34
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.model_selection import train_test_split\n",
        "x=df.drop(columns=[\"Disease\"])#all input columns\n",
        "y=df[[\"Disease\"]]\n",
        "from sklearn.model_selection import train_test_split\n",
        "x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7)\n",
        "x_train.head()\n",
        "import matplotlib.pyplot as plt\n",
        "from sklearn.preprocessing import RobustScaler\n",
        "rs=RobustScaler()\n",
        "rs_fit_transform_x_train=rs.fit_transform(x_train)\n",
        "rs_transform_x_test=rs.transform(x_test)\n",
        "plt.figure(figsize=(11,10))\n",
        "plt.hist(rs_fit_transform_x_train)\n",
        "pd.DataFrame(rs_fit_transform_x_train).skew()\n",
        "from sklearn.preprocessing import PowerTransformer\n",
        "pt = PowerTransformer()\n",
        "pt_fit_1=pt.fit_transform(rs_fit_transform_x_train)\n",
        "pt_transform_rs=pt.transform(rs_transform_x_test)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 830
        },
        "id": "8KL3p2TO5N4g",
        "outputId": "1345c52d-6c9a-4c74-b5ce-c954d3c8010f"
      },
      "execution_count": 70,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 1100x1000 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAA4wAAAMtCAYAAADUiv/pAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAANqdJREFUeJzt3X9wVfWd+P9XIJCImFBUEhkBEVuBNkrFFeO2/kBqtOjqynTRZSztsFrd6FRprdCxGvXT1aVau3ajdHct2NnaWtuqI1oVgz/aGlBRphSRUReLFhOmuiRqyw/hfP/YLxeibyiBhJMfj8fMnTn33nNzXzenkT7nfc+9RVmWZQEAAAAf0ifvAQAAAOiaBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgqznuAPbF169ZYu3ZtHHDAAVFUVJT3OAAAAN1KlmXx7rvvxtChQ6NPn52vI3bLYFy7dm0MGzYs7zEAAAC6tTfeeCMOPfTQnd7fLYPxgAMOiIj/e3FlZWU5TwMAANC9tLa2xrBhwwpttTPdMhi3vQ21rKxMMAIAAOyhv3aKnw+9AQAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQVJz3AABA52lYNKqwferE13KcBIDuyAojAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJLUrGOvq6qKoqKjNZfTo0YX7N2zYELW1tXHggQfGwIEDY8qUKdHc3NzmZ6xZsyYmT54cAwYMiCFDhsSVV14ZH3zwQce8GgAAADpMcXsf8MlPfjIef/zx7T+gePuPuOKKK+Khhx6Ke++9N8rLy+PSSy+Nc889N377299GRMSWLVti8uTJUVlZGc8880y89dZb8cUvfjH69esX//Iv/9IBLwcAAICO0u5gLC4ujsrKyo/c3tLSEnfeeWfcfffdMXHixIiImDdvXowZMyYWL14cxx9/fDz22GPx0ksvxeOPPx4VFRUxbty4uOGGG+Kqq66Kurq66N+//96/IgAAADpEu89hfOWVV2Lo0KFx+OGHx7Rp02LNmjUREbF06dLYvHlzTJo0qbDv6NGjY/jw4dHY2BgREY2NjVFVVRUVFRWFfWpqaqK1tTVWrFix0+fcuHFjtLa2trkAAADQudoVjBMmTIj58+fHI488EnfccUesXr06PvvZz8a7774bTU1N0b9//xg0aFCbx1RUVERTU1NERDQ1NbWJxW33b7tvZ2688cYoLy8vXIYNG9aesQEAANgD7XpL6hlnnFHYPuqoo2LChAkxYsSI+NnPfhb77bdfhw+3zezZs2PmzJmF662traIRAACgk+3V12oMGjQoPvGJT8Srr74alZWVsWnTpli/fn2bfZqbmwvnPFZWVn7kU1O3XU+dF7lNSUlJlJWVtbkAAADQufYqGN9777147bXX4pBDDonx48dHv379oqGhoXD/qlWrYs2aNVFdXR0REdXV1bF8+fJYt25dYZ+FCxdGWVlZjB07dm9GAQAAoIO16y2pX//61+Oss86KESNGxNq1a+Paa6+Nvn37xvnnnx/l5eUxY8aMmDlzZgwePDjKysrisssui+rq6jj++OMjIuK0006LsWPHxgUXXBBz5syJpqamuPrqq6O2tjZKSko65QUCAACwZ9oVjG+++Wacf/758fbbb8fBBx8cn/nMZ2Lx4sVx8MEHR0TErbfeGn369IkpU6bExo0bo6amJm6//fbC4/v27RsLFiyISy65JKqrq2P//feP6dOnx/XXX9+xrwoAAIC9VpRlWZb3EO3V2toa5eXl0dLS4nxGANiFhkWjCtunTnwtx0kA6Ep2t6n26hxGAAAAei7BCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACApOK8BwAA6K3enPXrwvahN302x0kA0qwwAgAAkCQYAQAASBKMAAAAJDmHEQDotZxDCLBrVhgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACApOK8BwCAvNwy9czC9tfuWZDjJADQNVlhBAAAIEkwAgAAkOQtqQBAj1F1V1Vhe/n05TlOAtAzWGEEAAAgSTACAACQJBgBAABIEowAAAAk+dAbgN20cvSYwvaYl1fmOAkAwL5hhREAAIAkK4wAwG6pv3hRYbt27sQcJwFgX7HCCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQV5z0AQHd3y9QzC9tfu2dBpz9f/cWL2lyvnTux058TAOidrDACAACQJBgBAABIEowAAAAkOYcRAOhVdjzveOrIq3KcBKDrs8IIAABAkmAEAAAgSTACAACQ5BxGACBp5egxbW84uT6fQQDIjRVGAAAAkgQjAAAASYIRAACAJOcwAkAODpv1UGH79Zsm5zgJAOycFUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEjyPYxAr+f78AAA0qwwAgAAkCQYAQAASBKMAAAAJDmHEYCeoa58h+2W/OYAgB7ECiMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEl7FYw33XRTFBUVxeWXX164bcOGDVFbWxsHHnhgDBw4MKZMmRLNzc1tHrdmzZqYPHlyDBgwIIYMGRJXXnllfPDBB3szCgAQEXV1dW0uALA39jgYn3vuufjBD34QRx11VJvbr7jiinjwwQfj3nvvjaeeeirWrl0b5557buH+LVu2xOTJk2PTpk3xzDPPxF133RXz58+Pa665Zs9fBQAAAB1uj4Lxvffei2nTpsV//ud/xsc+9rHC7S0tLXHnnXfGd7/73Zg4cWKMHz8+5s2bF88880wsXrw4IiIee+yxeOmll+K///u/Y9y4cXHGGWfEDTfcEPX19bFp06aOeVUAAADstT0Kxtra2pg8eXJMmjSpze1Lly6NzZs3t7l99OjRMXz48GhsbIyIiMbGxqiqqoqKiorCPjU1NdHa2horVqxIPt/GjRujtbW1zQUAAIDOVdzeB/z0pz+NF154IZ577rmP3NfU1BT9+/ePQYMGtbm9oqIimpqaCvvsGIvb7t92X8qNN94Y1113XXtHBQAAYC+0a4XxjTfeiK9+9avx4x//OEpLSztrpo+YPXt2tLS0FC5vvPHGPntuAACA3qpdwbh06dJYt25dHHPMMVFcXBzFxcXx1FNPxW233RbFxcVRUVERmzZtivXr17d5XHNzc1RWVkZERGVl5Uc+NXXb9W37fFhJSUmUlZW1uQAAANC52hWMp556aixfvjyWLVtWuBx77LExbdq0wna/fv2ioaGh8JhVq1bFmjVrorq6OiIiqqurY/ny5bFu3brCPgsXLoyysrIYO3ZsB70sAAAA9la7zmE84IAD4lOf+lSb2/bff/848MADC7fPmDEjZs6cGYMHD46ysrK47LLLorq6Oo4//viIiDjttNNi7NixccEFF8ScOXOiqakprr766qitrY2SkpIOelkAAADsrXZ/6M1fc+utt0afPn1iypQpsXHjxqipqYnbb7+9cH/fvn1jwYIFcckll0R1dXXsv//+MX369Lj++us7ehQAAAD2wl4H45NPPtnmemlpadTX10d9ff1OHzNixIh4+OGH9/apAQAA6ER79D2MAAAA9HyCEQAAgCTBCAAAQFKHf+gNAB1v5egx26+cvPNzxAG6jbryHbZb8psD2CUrjAAAACRZYQTYBxoWjWpz/dSJr+U0CQDA7rPCCAAAQJIVRgDI247nckU4nwuALsMKIwAAAEmCEQAAgCTBCAAAQJJzGAGATlf5xLI215tOGZfLHAC0jxVGAAAAkgQjAAAASYIRAACAJMEIAABAkg+9AYBuov7iRYXt2rkTc5wEgN7CCiMAAABJghEAAIAkb0kFAAqq7qoqbP8sxzkA6BqsMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJLvYQSALmzl6DHbr5xcn98gAPRKVhgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQV5z0AALBvVD6xrLDddMq43Obo7g6b9VBh+/WbJuc4CUDns8IIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQV5z0AAOypw2Y9VNh+vTTHQQCgh7LCCAAAQJJgBAAAIEkwAgAAkCQYAQAASPKhNwBAh6mrq0tuA9A9WWEEAAAgSTACAACQJBgBAABIcg4jAEAHWzl6TJvrY15emdMkAHvHCiMAAABJghEAAIAkwQgAAECScxgBgB5px/MInUMIsGesMAIAAJBkhREA6BQNi0Ztv1L0i/wGAWCPWWEEAAAgSTACAACQJBgBAABIEowAAAAk+dAbADpGXfmHrrfkMwcA0GGsMAIAAJAkGAEAAEjyllQAAHaq/uJFhe3auRNznATIgxVGAAAAkgQjAAAASd6SCgCQ0LBoVGH71Imv5TgJQH4EIwDspsonlhW2m04Zl9scALCvCEaATlJXV1fY/uyJ+c0BALCnnMMIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgqznsAAICeoOquqsL2z3KcA6AjCUYAYK+8OevX26+U5jcHAB1PMALsgfqLF+U9AgBAp3MOIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkORTUgEAurDKJ5a1ud50yrhc5gB6JyuMAAAAJAlGAAAAkgQjAAAASc5hBGCPHTbrocL266U5DtIL3TL1zML21+5ZkOMkAPRkghGALqeuri653VueHwC6Cm9JBQAAIEkwAgAAkOQtqQB0CW/O+vX2K86HBIAuwQojAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABI8rUaAD3Ijl9NcehNn81xEgCgJxCMALALDYtGbb9S9Iv8BgGAHHhLKgAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAktoVjHfccUccddRRUVZWFmVlZVFdXR2/+tWvCvdv2LAhamtr48ADD4yBAwfGlClTorm5uc3PWLNmTUyePDkGDBgQQ4YMiSuvvDI++OCDjnk1AAAAdJh2BeOhhx4aN910UyxdujSef/75mDhxYpx99tmxYsWKiIi44oor4sEHH4x77703nnrqqVi7dm2ce+65hcdv2bIlJk+eHJs2bYpnnnkm7rrrrpg/f35cc801HfuqAAAA2GvF7dn5rLPOanP929/+dtxxxx2xePHiOPTQQ+POO++Mu+++OyZOnBgREfPmzYsxY8bE4sWL4/jjj4/HHnssXnrppXj88cejoqIixo0bFzfccENcddVVUVdXF/37908+78aNG2Pjxo2F662tre19nQAAALTTHp/DuGXLlvjpT38a77//flRXV8fSpUtj8+bNMWnSpMI+o0ePjuHDh0djY2NERDQ2NkZVVVVUVFQU9qmpqYnW1tbCKmXKjTfeGOXl5YXLsGHD9nRsAAAAdlO7g3H58uUxcODAKCkpiYsvvjjuu+++GDt2bDQ1NUX//v1j0KBBbfavqKiIpqamiIhoampqE4vb7t92387Mnj07WlpaCpc33nijvWMDAADQTu16S2pExJFHHhnLli2LlpaW+PnPfx7Tp0+Pp556qjNmKygpKYmSkpJOfQ4AAADaancw9u/fP4444oiIiBg/fnw899xz8W//9m8xderU2LRpU6xfv77NKmNzc3NUVlZGRERlZWU8++yzbX7etk9R3bYPAAAAXcNefw/j1q1bY+PGjTF+/Pjo169fNDQ0FO5btWpVrFmzJqqrqyMiorq6OpYvXx7r1q0r7LNw4cIoKyuLsWPH7u0oAAB0YYfNeqhwAbqHdq0wzp49O84444wYPnx4vPvuu3H33XfHk08+GY8++miUl5fHjBkzYubMmTF48OAoKyuLyy67LKqrq+P444+PiIjTTjstxo4dGxdccEHMmTMnmpqa4uqrr47a2lpvOQUAAOhi2hWM69atiy9+8Yvx1ltvRXl5eRx11FHx6KOPxuc+97mIiLj11lujT58+MWXKlNi4cWPU1NTE7bffXnh83759Y8GCBXHJJZdEdXV17L///jF9+vS4/vrrO/ZVAQAAsNfaFYx33nnnLu8vLS2N+vr6qK+v3+k+I0aMiIcffrg9TwsAdLAd3xL4+k2Tc5wEgK5sr89hBAAAoGdq96ekAkB3snL0mML2mJdX5jgJAHQ/VhgBAABIssIIAL1dXfn27ZHD85ujC6t8YllhuzS/MQD2OSuMAAAAJFlhBADa7ZapZxa2p468KsdJAOhMVhgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQV5z0AAEBvcsvUMwvbU0deleMkAH+dFUYAAACSBCMAAABJghEAAIAk5zAC5OywWQ8Vtl+/aXKH/dy6urrk9r5SdVdVYftnN35Q2B7z8sp9Pkt30+Z3l+McAGCFEQAAgCTBCAAAQJJgBAAAIMk5jAA7qivfYbslvzkAALoAK4wAAAAkWWEEoMfxKaMA0DGsMAIAAJAkGAEAAEjyllSAXqbyiWWF7aZTxuU2x57acf7S/MYAgF7BCiMAAABJghEAAIAkwQgAAECScxgBupK68h22W/KbAwAgrDACAACwE4IRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAICk4rwHAKB3qb94UWG7du7EHCcBAP4aK4wAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACDJ12oAAOypuvLt2yOH5zcHQCcRjAAAEVFXV9fm+mdPzGcOgK7EW1IBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkn5IKAHQrh816qM3112+anNMkAD2fFUYAAACSBCMAAABJghEAAIAk5zACdKA3Z/16+5XS/OYAAOgIghEA6PHqL16U9wgA3ZK3pAIAAJBkhRGgi6q6q6qw/bMc5wAAei8rjAAAACQJRgAAAJIEIwAAAEmCEQAAgCQfegMA0MU0LBq1/UrRL/IbBOj1rDACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgqznsAgK6q6q6qNtd/ltMcAAB5scIIAABAkmAEAAAgyVtSASAi3pz16+1XSvObg56p/uJFeY/Qbe34u6udOzHHSaB3EoxAl7Pj/3E/9KbP5jgJAEDv5i2pAAAAJAlGAAAAkgQjAAAASYIRAACAJB96A3xER37oTNVdVYXt5dOX79XPAgBg37LCCAAAQJIVRgByc8vUMwvbU0deleMkAECKFUYAAACSBCMAAABJghEAAIAkwQgAAECSD70BcrfjB59E+PATAICuwgojAAAASVYYAYDura58+/bI4fnNAdADCUYAgC6grq6usP3ZE/Obo6epfGJZYbvplHG5zQHdlbekAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJF+rAQDQW+34HZZ1LfnNAXRZVhgBAABIEowAAAAkeUsqQC/QsGjU9itFv8hvEACgWxGMADmofGJZYbs0vzEAAHZJMAJ7ZMfgiYhoOmVcLnMAANB5nMMIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSfK0GAACdxvfOQvdmhREAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEhqVzDeeOON8Td/8zdxwAEHxJAhQ+Kcc86JVatWtdlnw4YNUVtbGwceeGAMHDgwpkyZEs3NzW32WbNmTUyePDkGDBgQQ4YMiSuvvDI++OCDvX81AAAAdJh2BeNTTz0VtbW1sXjx4li4cGFs3rw5TjvttHj//fcL+1xxxRXx4IMPxr333htPPfVUrF27Ns4999zC/Vu2bInJkyfHpk2b4plnnom77ror5s+fH9dcc03HvSoAAAD2Wru+h/GRRx5pc33+/PkxZMiQWLp0aZx44onR0tISd955Z9x9990xceLEiIiYN29ejBkzJhYvXhzHH398PPbYY/HSSy/F448/HhUVFTFu3Li44YYb4qqrroq6urro379/x706AAAA9thencPY0tISERGDBw+OiIilS5fG5s2bY9KkSYV9Ro8eHcOHD4/GxsaIiGhsbIyqqqqoqKgo7FNTUxOtra2xYsWK5PNs3LgxWltb21wAAADoXO1aYdzR1q1b4/LLL4+//du/jU996lMREdHU1BT9+/ePQYMGtdm3oqIimpqaCvvsGIvb7t92X8qNN94Y11133Z6OCgBARBw266E2118vzWmQTtSwaFTbG4p+kc8g0EPscTDW1tbG73//+/jNb37TkfMkzZ49O2bOnFm43traGsOGDev05wWgZ6m/eFHeIwBAt7JHwXjppZfGggUL4umnn45DDz20cHtlZWVs2rQp1q9f32aVsbm5OSorKwv7PPvss21+3rZPUd22z4eVlJRESUnJnowKAADAHmrXOYxZlsWll14a9913XyxatChGjhzZ5v7x48dHv379oqGhoXDbqlWrYs2aNVFdXR0REdXV1bF8+fJYt25dYZ+FCxdGWVlZjB07dm9eCwAAAB2oXSuMtbW1cffdd8cDDzwQBxxwQOGcw/Ly8thvv/2ivLw8ZsyYETNnzozBgwdHWVlZXHbZZVFdXR3HH398REScdtppMXbs2Ljgggtizpw50dTUFFdffXXU1tZaRQQAAOhC2hWMd9xxR0REnHzyyW1unzdvXnzpS1+KiIhbb701+vTpE1OmTImNGzdGTU1N3H777YV9+/btGwsWLIhLLrkkqqurY//994/p06fH9ddfv3evBAAAgA7VrmDMsuyv7lNaWhr19fVRX1+/031GjBgRDz/8cHueGgAAkurq6grbnz0xvzmgJ9qr72EEAACg5xKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJBUnPcAAADkr+quqsL28unLc5wE6EqsMAIAAJAkGAEAAEgSjAAAACQJRgAAAJJ86A0AALvllqlnFra/ds+CHCcB9hUrjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAUnHeAwAA0P3V1dUlt4HuzQojAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQV5z0A9DYNi0YVtk+d+FqOkwAAwK5ZYQQAACBJMAIAAJAkGAEAAEhyDiMAAN3CLVPPLGx/7Z4FOU4CvYcVRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkorzHgDoXFV3VbW5vnz68pwmAQCgu7HCCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQVJz3AAAAdD9vzvp12xtK85kD6FxWGAEAAEiywgg9UV359u2Rw/ObAwCAbs0KIwAAAEmCEQAAgCTBCAAAQJJzGAGgm2vzaZU+qRKADiQYAejSGhaNantD0S/yGQQAeiFvSQUAACBJMAIAAJDkLanAbmvz1kBvCwQA6PGsMAIAAJBkhREAgDZWjh6z/crJ9fkNAuTOCiMAAABJVhgBurlbpp5Z2J468qocJwEAehorjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkOR7GAEAyFXVXVVtri+fvjynSYAPs8IIAABAkmAEAAAgSTACAACQJBgBAABI8qE3AACQo7q6uuQ2dAVWGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCSfkgoAQIdqWDRq+5WiX+Q3CLDXrDACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkX6sBAECXsnL0mO1XTq7PbxDACiMAAABpghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACS1OxiffvrpOOuss2Lo0KFRVFQU999/f5v7syyLa665Jg455JDYb7/9YtKkSfHKK6+02eedd96JadOmRVlZWQwaNChmzJgR77333l69EKDna1g0qnABAKDztTsY33///Tj66KOjvj79Japz5syJ2267LebOnRtLliyJ/fffP2pqamLDhg2FfaZNmxYrVqyIhQsXxoIFC+Lpp5+Oiy66aM9fBQAAAB2uuL0POOOMM+KMM85I3pdlWXzve9+Lq6++Os4+++yIiPjRj34UFRUVcf/998d5550XK1eujEceeSSee+65OPbYYyMi4vvf/358/vOfj5tvvjmGDh26Fy8HAACAjtKh5zCuXr06mpqaYtKkSYXbysvLY8KECdHY2BgREY2NjTFo0KBCLEZETJo0Kfr06RNLlixJ/tyNGzdGa2trmwsAAACdq0ODsampKSIiKioq2txeUVFRuK+pqSmGDBnS5v7i4uIYPHhwYZ8Pu/HGG6O8vLxwGTZsWEeODQAAQEK3+JTU2bNnR0tLS+Hyxhtv5D0SAABAj9ehwVhZWRkREc3NzW1ub25uLtxXWVkZ69ata3P/Bx98EO+8805hnw8rKSmJsrKyNhcAAAA6V4cG48iRI6OysjIaGhoKt7W2tsaSJUuiuro6IiKqq6tj/fr1sXTp0sI+ixYtiq1bt8aECRM6chwAAAD2Qrs/JfW9996LV199tXB99erVsWzZshg8eHAMHz48Lr/88vh//+//xcc//vEYOXJkfOtb34qhQ4fGOeecExERY8aMidNPPz0uvPDCmDt3bmzevDkuvfTSOO+883xCKgAAdIJbpp5Z2P7aPQtynITupt3B+Pzzz8cpp5xSuD5z5syIiJg+fXrMnz8/vvGNb8T7778fF110Uaxfvz4+85nPxCOPPBKlpaWFx/z4xz+OSy+9NE499dTo06dPTJkyJW677bYOeDkAANC1vTnr121vKE3vB11Bu4Px5JNPjizLdnp/UVFRXH/99XH99dfvdJ/BgwfH3Xff3d6nBgAAYB/qFp+SCgAAwL4nGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJBXnPQCQn/qLFxW2a+dOzHESAAC6IiuMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkCUYAAACSBCMAAABJghEAAICk4rwHAHqPlaPHFLbHvLwyx0kAANgdVhgBAABIssIIAAC9VF1dXXIbtrHCCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIKs57AAAAgO6mrq5ul9d7CiuMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgyddqAABAe9WV77Ddkt8c0MmsMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCRfqwEAQLfz5qxfb79Smt8c0NNZYQQAACBJMAIAAJAkGAEAAEhyDiPdQtVdVYXt5dOX5zgJ+1pdXV1h+7Mnbr+98ollhe2mU8bts3kAoLfwby0RVhgBAADYCcEIAABAkrekQi+zcvSY7VdOrs9vEAAAujwrjAAAACRZYYR9YGcf3NKTHDbrocL26zdNznESAAA6ihVGAAAAkqwwAgBAD1R/8aK8R6AHsMIIAABAkmAEAAAgyVtSAQCAbmnHDxbccbvyiWWF7aZTxu2zeXoiwQgAALCXGhaNKmyfOvG1HCfpWIIRiIiIW6aeWdieOvKqHCcBAHZX1V1Vba4vn748p0noqZzDCAAAQJIVRgAA2A2HzXqosP16aY6DwD4kGIFc+G4oAICuz1tSAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIKs57ALqPurq65DYAAB2v8ollhe2mU8blNge9mxVGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAkFec9AAAAkL+GRaPa3lD0i3wGoUuxwggAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACT5lFQAAOhkt0w9s7A9deRVOU4C7SMYAQCgO6kr3749cnh+c9AreEsqAAAASYIRAACAJG9Jhd1QdVdVYXv59OU5TgIAAPuOFUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJIEIwAAAEmCEQAAgCTBCAAAQJJgBAAAIEkwAgAAkCQYAQAASBKMAAAAJAlGAAAAkgQjAAAASYIRAACAJMEIAABAkmAEAAAgSTACAACQJBgBAABIEowAAAAk5RqM9fX1cdhhh0VpaWlMmDAhnn322TzHAQAAYAe5BeM999wTM2fOjGuvvTZeeOGFOProo6OmpibWrVuX10gAAADsoDivJ/7ud78bF154YXz5y1+OiIi5c+fGQw89FD/84Q9j1qxZbfbduHFjbNy4sXC9paUlIiJaW1v33cC0OQb7+ne/5S9bcnvujnj+HX9377+/da9+1u49YVbY3HH2iIj3tmy//pdN729/yObNhe13N26/fccZd5x9a9F7bX7u1o1/Tj5mx+ffnef+8PNvLEr/7nZ8/r39PbaZvajjfnc7mz2i7fy78/w7e+49ef598buLaP+x97vbrqN+dxE7n7+9v7s9ef5d/Tdjb35/O84e0f5j73e3w8/qoN9dxO7Nn/d/bzvt73Y3fu6G3fzd7Tjj1vd3Mvsu/p3fcb+d/e523Gdn/x8lomN/d51lZ///dKe/u0567oh99P/xOtC2GbMs2+V+Rdlf26MTbNq0KQYMGBA///nP45xzzincPn369Fi/fn088MADbfavq6uL6667bh9PCQAA0LO98cYbceihh+70/lxWGP/0pz/Fli1boqKios3tFRUV8fLLL39k/9mzZ8fMmTML17du3RrvvPNOHHjggVFUVNTp8+6O1tbWGDZsWLzxxhtRVlaW9zj8/xyXrslx6bocm67JcemaHJeuyXHpuhybriXLsnj33Xdj6NChu9wvt7ektkdJSUmUlJS0uW3QoEH5DPNXlJWV+QPoghyXrslx6bocm67JcemaHJeuyXHpuhybrqO8vPyv7pPLh94cdNBB0bdv32hubm5ze3Nzc1RWVuYxEgAAAB+SSzD2798/xo8fHw0NDYXbtm7dGg0NDVFdXZ3HSAAAAHxIbm9JnTlzZkyfPj2OPfbYOO644+J73/tevP/++4VPTe1uSkpK4tprr/3IW2fJl+PSNTkuXZdj0zU5Ll2T49I1OS5dl2PTPeXyKanb/Pu//3t85zvfiaamphg3blzcdtttMWHChLzGAQAAYAe5BiMAAABdVy7nMAIAAND1CUYAAACSBCMAAABJghEAAIAkwbiHXn/99ZgxY0aMHDky9ttvvxg1alRce+21sWnTpl0+bsOGDVFbWxsHHnhgDBw4MKZMmRLNzc37aOre4dvf/naccMIJMWDAgBg0aNBuPeZLX/pSFBUVtbmcfvrpnTtoL7MnxyXLsrjmmmvikEMOif322y8mTZoUr7zySucO2su88847MW3atCgrK4tBgwbFjBkz4r333tvlY04++eSP/L1cfPHF+2jinqu+vj4OO+ywKC0tjQkTJsSzzz67y/3vvffeGD16dJSWlkZVVVU8/PDD+2jS3qU9x2X+/Pkf+dsoLS3dh9P2Dk8//XScddZZMXTo0CgqKor777//rz7mySefjGOOOSZKSkriiCOOiPnz53f6nL1Ne4/Lk08++ZG/l6Kiomhqato3A7PbBOMeevnll2Pr1q3xgx/8IFasWBG33nprzJ07N775zW/u8nFXXHFFPPjgg3HvvffGU089FWvXro1zzz13H03dO2zatCm+8IUvxCWXXNKux51++unx1ltvFS4/+clPOmnC3mlPjsucOXPitttui7lz58aSJUti//33j5qamtiwYUMnTtq7TJs2LVasWBELFy6MBQsWxNNPPx0XXXTRX33chRde2ObvZc6cOftg2p7rnnvuiZkzZ8a1114bL7zwQhx99NFRU1MT69atS+7/zDPPxPnnnx8zZsyIF198Mc4555w455xz4ve///0+nrxna+9xiYgoKytr87fxhz/8YR9O3Du8//77cfTRR0d9ff1u7b969eqYPHlynHLKKbFs2bK4/PLL45/+6Z/i0Ucf7eRJe5f2HpdtVq1a1eZvZsiQIZ00IXsso8PMmTMnGzly5E7vX79+fdavX7/s3nvvLdy2cuXKLCKyxsbGfTFirzJv3rysvLx8t/adPn16dvbZZ3fqPPyf3T0uW7duzSorK7PvfOc7hdvWr1+flZSUZD/5yU86ccLe46WXXsoiInvuuecKt/3qV7/KioqKsj/+8Y87fdxJJ52UffWrX90HE/Yexx13XFZbW1u4vmXLlmzo0KHZjTfemNz/H/7hH7LJkye3uW3ChAnZV77ylU6ds7dp73Fpz787dIyIyO67775d7vONb3wj++QnP9nmtqlTp2Y1NTWdOFnvtjvH5YknnsgiIvvf//3ffTITe84KYwdqaWmJwYMH7/T+pUuXxubNm2PSpEmF20aPHh3Dhw+PxsbGfTEiu/Dkk0/GkCFD4sgjj4xLLrkk3n777bxH6tVWr14dTU1Nbf5eysvLY8KECf5eOkhjY2MMGjQojj322MJtkyZNij59+sSSJUt2+dgf//jHcdBBB8WnPvWpmD17dvz5z3/u7HF7rE2bNsXSpUvb/G+9T58+MWnSpJ3+b72xsbHN/hERNTU1/jY60J4cl4iI9957L0aMGBHDhg2Ls88+O1asWLEvxmUX/L10bePGjYtDDjkkPve5z8Vvf/vbvMchoTjvAXqKV199Nb7//e/HzTffvNN9mpqaon///h85f6uiosL7tXN2+umnx7nnnhsjR46M1157Lb75zW/GGWecEY2NjdG3b9+8x+uVtv1NVFRUtLnd30vHaWpq+shbf4qLi2Pw4MG7/B3/4z/+Y4wYMSKGDh0av/vd7+Kqq66KVatWxS9/+cvOHrlH+tOf/hRbtmxJ/m/95ZdfTj6mqanJ30Yn25PjcuSRR8YPf/jDOOqoo6KlpSVuvvnmOOGEE2LFihVx6KGH7ouxSdjZ30tra2v85S9/if322y+nyXq3Qw45JObOnRvHHntsbNy4Mf7rv/4rTj755FiyZEkcc8wxeY/HDqwwfsisWbOSJ+DuePnwPxR//OMf4/TTT48vfOELceGFF+Y0ec+2J8elPc4777z4u7/7u6iqqopzzjknFixYEM8991w8+eSTHfcieqDOPi7smc4+LhdddFHU1NREVVVVTJs2LX70ox/FfffdF6+99loHvgrofqqrq+OLX/xijBs3Lk466aT45S9/GQcffHD84Ac/yHs06HKOPPLI+MpXvhLjx4+PE044IX74wx/GCSecELfeemveo/EhVhg/5Gtf+1p86Utf2uU+hx9+eGF77dq1ccopp8QJJ5wQ//Ef/7HLx1VWVsamTZti/fr1bVYZm5ubo7Kycm/G7vHae1z21uGHHx4HHXRQvPrqq3Hqqad22M/taTrzuGz7m2hubo5DDjmkcHtzc3OMGzduj35mb7G7x6WysvIjH97xwQcfxDvvvNOu/yZNmDAhIv7vnRajRo1q97y93UEHHRR9+/b9yCdm7+rfhsrKynbtT/vtyXH5sH79+sWnP/3pePXVVztjRHbTzv5eysrKrC52Mccdd1z85je/yXsMPkQwfsjBBx8cBx988G7t+8c//jFOOeWUGD9+fMybNy/69Nn1gu348eOjX79+0dDQEFOmTImI//tkqDVr1kR1dfVez96Ttee4dIQ333wz3n777Tahwkd15nEZOXJkVFZWRkNDQyEQW1tbY8mSJe3+BNzeZnePS3V1daxfvz6WLl0a48ePj4iIRYsWxdatWwsRuDuWLVsWEeHvZQ/1798/xo8fHw0NDXHOOedERMTWrVujoaEhLr300uRjqquro6GhIS6//PLCbQsXLvRvSQfak+PyYVu2bInly5fH5z//+U6clL+murr6I1874++la1q2bJl/S7qivD91p7t68803syOOOCI79dRTszfffDN76623Cpcd9znyyCOzJUuWFG67+OKLs+HDh2eLFi3Knn/++ay6ujqrrq7O4yX0WH/4wx+yF198MbvuuuuygQMHZi+++GL24osvZu+++25hnyOPPDL75S9/mWVZlr377rvZ17/+9ayxsTFbvXp19vjjj2fHHHNM9vGPfzzbsGFDXi+jx2nvccmyLLvpppuyQYMGZQ888ED2u9/9Ljv77LOzkSNHZn/5y1/yeAk90umnn559+tOfzpYsWZL95je/yT7+8Y9n559/fuH+D/937NVXX82uv/767Pnnn89Wr16dPfDAA9nhhx+enXjiiXm9hB7hpz/9aVZSUpLNnz8/e+mll7KLLrooGzRoUNbU1JRlWZZdcMEF2axZswr7//a3v82Ki4uzm2++OVu5cmV27bXXZv369cuWL1+e10vokdp7XK677rrs0UcfzV577bVs6dKl2XnnnZeVlpZmK1asyOsl9Ejvvvtu4d+QiMi++93vZi+++GL2hz/8IcuyLJs1a1Z2wQUXFPb/n//5n2zAgAHZlVdema1cuTKrr6/P+vbtmz3yyCN5vYQeqb3H5dZbb83uv//+7JVXXsmWL1+effWrX8369OmTPf7443m9BHZCMO6hefPmZRGRvGyzevXqLCKyJ554onDbX/7yl+yf//mfs4997GPZgAEDsr//+79vE5nsvenTpyePy47HISKyefPmZVmWZX/+85+z0047LTv44IOzfv36ZSNGjMguvPDCwv8hoGO097hk2f99tca3vvWtrKKiIispKclOPfXUbNWqVft++B7s7bffzs4///xs4MCBWVlZWfblL3+5TcR/+L9ja9asyU488cRs8ODBWUlJSXbEEUdkV155ZdbS0pLTK+g5vv/972fDhw/P+vfvnx133HHZ4sWLC/eddNJJ2fTp09vs/7Of/Sz7xCc+kfXv3z/75Cc/mT300EP7eOLeoT3H5fLLLy/sW1FRkX3+85/PXnjhhRym7tm2fR3Dhy/bjsX06dOzk0466SOPGTduXNa/f//s8MMPb/NvDR2jvcflX//1X7NRo0ZlpaWl2eDBg7OTTz45W7RoUT7Ds0tFWZZlnb+OCQAAQHfjU1IBAABIEowAAAAkCUYAAACSBCMAAABJghEAAIAkwQgAAECSYAQAACBJMAIAAJAkGAEAAEgSjAAAACQJRgAAAJL+P3+q7i3Ib+1UAAAAAElFTkSuQmCC\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.decomposition import PCA\n",
        "pca=PCA()\n",
        "pca_fit_pt=pca.fit_transform(pt_fit_1)\n",
        "pca_transform=pca.transform(pt_transform_rs)\n",
        "plt.hist(pca_fit_pt)\n",
        "y_train.head()\n",
        "from sklearn.preprocessing import LabelEncoder\n",
        "le_target=LabelEncoder()\n",
        "le_y_train=le_target.fit_transform(y_train)\n",
        "le_y_test=le_target.transform(y_test)\n",
        "le_y_train"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 541
        },
        "id": "lM3YnU9jAd_E",
        "outputId": "5043b593-b916-4538-e7a2-9dd762e0b556"
      },
      "execution_count": 80,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().\n",
            "  y = column_or_1d(y, warn=True)\n",
            "/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().\n",
            "  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "array([2, 3, 0, ..., 1, 0, 3])"
            ]
          },
          "metadata": {},
          "execution_count": 80
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 640x480 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjAAAAGdCAYAAAAMm0nCAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAAJQRJREFUeJzt3X9U1fXhx/HXRQXUBMTFvXISZayTulg2SaJfJ5MjNW155pqesWLNo+mgzfweC74nlewH5frhdJS1H+o2XbbtmKXlZGDaJqJRbIbmWrOBugttDK6yr6Dw+f5hfNo1LNHP5XPfl+fjnM+R+/m8772vjz/g5ft+fngsy7IEAABgkCi3AwAAAPQUBQYAABiHAgMAAIxDgQEAAMahwAAAAONQYAAAgHEoMAAAwDgUGAAAYJz+bgcIlc7OTh09elRDhgyRx+NxOw4AADgHlmXp2LFjSk5OVlTU2edZIrbAHD16VCNGjHA7BgAAOA/19fW65JJLzro9YgvMkCFDJJ3+DYiLi3M5DQAAOBeBQEAjRoywf46fTcQWmK6PjeLi4igwAAAY5rMO/+AgXgAAYBwKDAAAMA4FBgAAGIcCAwAAjEOBAQAAxqHAAAAA41BgAACAcSgwAADAOBQYAABgHAoMAAAwDgUGAAAYhwIDAACMQ4EBAADGocAAAADjUGAAwGG+7TXyba9xOwYQ0SgwAADAOBQYAABgHAoMAAAwTo8LzM6dO3XrrbcqOTlZHo9HL730UtB2y7K0ePFiDR8+XAMHDlR2drbee++9oDFNTU3Kzc1VXFycEhISNGvWLB0/fjxozJ///Gddf/31io2N1YgRI7Rs2bKe7x0AAIhIPS4wra2tuuKKK1RaWtrt9mXLlmnFihVatWqVqqqqNHjwYOXk5OjEiRP2mNzcXNXW1qqsrEybN2/Wzp07NWfOHHt7IBDQ5MmTNXLkSFVXV+sHP/iBiouL9fzzz5/HLgIAgIhjXQBJ1saNG+3HnZ2dls/ns37wgx/Y65qbm62YmBjrV7/6lWVZlrV//35LkrV37157zGuvvWZ5PB7ryJEjlmVZ1jPPPGMNHTrUamtrs8fcf//91mWXXXbO2VpaWixJVktLy/nuHgCcF2/F25a34m23YwBGOtef344eA3Po0CH5/X5lZ2fb6+Lj45WZmanKykpJUmVlpRISEpSRkWGPyc7OVlRUlKqqquwxN9xwg6Kjo+0xOTk5OnjwoP797393+95tbW0KBAJBCwAAiEyOFhi/3y9J8nq9Qeu9Xq+9ze/3KykpKWh7//79lZiYGDSmu9f47/c4U0lJieLj4+1lxIgRF75DAAAgLEXMWUhFRUVqaWmxl/r6ercjAQCAEHG0wPh8PklSQ0ND0PqGhgZ7m8/nU2NjY9D2U6dOqampKWhMd6/x3+9xppiYGMXFxQUtAAAgMjlaYFJTU+Xz+VReXm6vCwQCqqqqUlZWliQpKytLzc3Nqq6utsdUVFSos7NTmZmZ9pidO3fq5MmT9piysjJddtllGjp0qJORAQCAgXpcYI4fP66amhrV1NRIOn3gbk1Njerq6uTxeDR//nw9/PDDevnll7Vv3z7deeedSk5O1rRp0yRJY8aM0c0336zZs2drz549+uMf/6iCggLNnDlTycnJkqRvfvObio6O1qxZs1RbW6sNGzbohz/8oRYsWODYjgMAAHP17+kT3nzzTU2cONF+3FUq8vLytGbNGt13331qbW3VnDlz1NzcrOuuu05bt25VbGys/Zx169apoKBAkyZNUlRUlKZPn64VK1bY2+Pj47Vt2zbl5+dr/Pjx+tznPqfFixcHXSsGAAD0XR7Lsiy3Q4RCIBBQfHy8WlpaOB4GQK/quhO1f+I4V3MAJjrXn98RcxYSAADoOygwAADAOBQYAABgHAoMAAAwDgUGAAAYhwIDAACMQ4EBAADGocAAAADjUGAAAIBxKDAAAMA4FBgAAGAcCgwAADAOBQYAABiHAgMAAIxDgQEAAMahwAAAAONQYAAAgHEoMAAAwDgUGAAAYBwKDAA4qLwize0IQJ9AgQEAAMahwAAAAONQYAAAgHEoMAAAwDgUGAAAYBwKDAAAMA4FBgAAGIcCAwAAjEOBAQAAxqHAAAAA41BgAACAcSgwAADAOP3dDgAAkaC4uFiSdP0N7uYA+gpmYAAAgHEoMAAAwDgUGAAAYBwKDAAAMA4FBgAAGIcCAwAAjEOBAQAAxqHAAAAA41BgAACAcSgwAADAOBQYAABgHAoMAAAwDgUGAAAYhwIDAACMQ4EBAADGocAAAADjUGAAAIBxKDAAAMA4FBgAAGAcCgwAADAOBQYAABiHAgMAAIxDgQEAAMahwAAAAONQYAAAgHEcLzAdHR1atGiRUlNTNXDgQKWlpemhhx6SZVn2GMuytHjxYg0fPlwDBw5Udna23nvvvaDXaWpqUm5uruLi4pSQkKBZs2bp+PHjTscFAAAGcrzAPP7443r22Wf1ox/9SAcOHNDjjz+uZcuWaeXKlfaYZcuWacWKFVq1apWqqqo0ePBg5eTk6MSJE/aY3Nxc1dbWqqysTJs3b9bOnTs1Z84cp+MCAAAD9Xf6BXft2qXbbrtNU6ZMkSSNGjVKv/rVr7Rnzx5Jp2dfli9frgceeEC33XabJOnnP/+5vF6vXnrpJc2cOVMHDhzQ1q1btXfvXmVkZEiSVq5cqa985St64oknlJyc7HRsAABgEMdnYK655hqVl5frL3/5iyTpT3/6k/7whz/olltukSQdOnRIfr9f2dnZ9nPi4+OVmZmpyspKSVJlZaUSEhLs8iJJ2dnZioqKUlVVVbfv29bWpkAgELQAAIDI5PgMTGFhoQKBgEaPHq1+/fqpo6NDjzzyiHJzcyVJfr9fkuT1eoOe5/V67W1+v19JSUnBQfv3V2Jioj3mTCUlJXrwwQed3h0AABCGHJ+BefHFF7Vu3TqtX79eb731ltauXasnnnhCa9eudfqtghQVFamlpcVe6uvrQ/p+AADAPY7PwCxcuFCFhYWaOXOmJCk9PV1///vfVVJSory8PPl8PklSQ0ODhg8fbj+voaFB48aNkyT5fD41NjYGve6pU6fU1NRkP/9MMTExiomJcXp3AABAGHJ8BuY///mPoqKCX7Zfv37q7OyUJKWmpsrn86m8vNzeHggEVFVVpaysLElSVlaWmpubVV1dbY+pqKhQZ2enMjMznY4MAAAM4/gMzK233qpHHnlEKSkp+uIXv6i3335bTz31lL7zne9Ikjwej+bPn6+HH35Yl156qVJTU7Vo0SIlJydr2rRpkqQxY8bo5ptv1uzZs7Vq1SqdPHlSBQUFmjlzJmcgAQAA5wvMypUrtWjRIn33u99VY2OjkpOTdffdd2vx4sX2mPvuu0+tra2aM2eOmpubdd1112nr1q2KjY21x6xbt04FBQWaNGmSoqKiNH36dK1YscLpuAAAwEAe678vkRtBAoGA4uPj1dLSori4OLfjAIhwxcXFkqTrb/iFcj2/lST5J45zLxBgqHP9+c29kAAAgHEoMAAAwDgUGAAAYBwKDAAAMA4FBgAAGIcCAwAAjEOBAQAAxqHAAMB5eHLGVD05Y6rbMYA+iwIDAACMQ4EBAADGocAAwDk4MHqMDowe43YMAB+hwAAAAONQYAAAgHEoMAAAwDj93Q4AACY7XPjG6S9i3c0B9DXMwAAAAONQYAAAgHEoMAAAwDgUGAAAYBwKDAAAMA4FBgAAGIcCAwAAjEOBAQAAxqHAAAAA41BgAACAcSgwAADAOBQYAPgM6WvT3Y4A4AwUGAAAYBwKDAAAMA4FBgAAGIcCAwAAjEOBAQAAxqHAAAAA41BgAACAcSgwAADAOBQYAABgHAoMAAAwDgUGAAAYhwIDAACMQ4EBAADGocAAAADjUGAAAIBxKDAAAMA4FBgAAGAcCgwAADAOBQYAABiHAgMAAIxDgQEAAMahwAAAAONQYAAAgHEoMAAAwDgUGAAAYBwKDACcYVThFo0q3OJ2DACfggIDAACMQ4EB0OeVV6SpvCLN7RgAeoACAwAAjEOBAQAAxglJgTly5Ii+9a1vadiwYRo4cKDS09P15ptv2tsty9LixYs1fPhwDRw4UNnZ2XrvvfeCXqOpqUm5ubmKi4tTQkKCZs2apePHj4ciLgAAMIzjBebf//63rr32Wg0YMECvvfaa9u/fryeffFJDhw61xyxbtkwrVqzQqlWrVFVVpcGDBysnJ0cnTpywx+Tm5qq2tlZlZWXavHmzdu7cqTlz5jgdFwAAGKi/0y/4+OOPa8SIEVq9erW9LjU11f7asiwtX75cDzzwgG677TZJ0s9//nN5vV699NJLmjlzpg4cOKCtW7dq7969ysjIkCStXLlSX/nKV/TEE08oOTnZ6dgAAMAgjs/AvPzyy8rIyNDtt9+upKQkXXnllfrxj39sbz906JD8fr+ys7PtdfHx8crMzFRlZaUkqbKyUgkJCXZ5kaTs7GxFRUWpqqrK6cgAAMAwjheYv/3tb3r22Wd16aWX6ne/+53mzZun733ve1q7dq0kye/3S5K8Xm/Q87xer73N7/crKSkpaHv//v2VmJhojzlTW1ubAoFA0AIAACKT4x8hdXZ2KiMjQ48++qgk6corr9Q777yjVatWKS8vz+m3s5WUlOjBBx8M2esDAIDw4fgMzPDhwzV27NigdWPGjFFdXZ0kyefzSZIaGhqCxjQ0NNjbfD6fGhsbg7afOnVKTU1N9pgzFRUVqaWlxV7q6+sd2R8AABB+HC8w1157rQ4ePBi07i9/+YtGjhwp6fQBvT6fT+Xl5fb2QCCgqqoqZWVlSZKysrLU3Nys6upqe0xFRYU6OzuVmZnZ7fvGxMQoLi4uaAEAAJHJ8Y+Q7r33Xl1zzTV69NFH9Y1vfEN79uzR888/r+eff16S5PF4NH/+fD388MO69NJLlZqaqkWLFik5OVnTpk2TdHrG5uabb9bs2bO1atUqnTx5UgUFBZo5cyZnIAEAAOcLzFVXXaWNGzeqqKhIS5cuVWpqqpYvX67c3Fx7zH333afW1lbNmTNHzc3Nuu6667R161bFxsbaY9atW6eCggJNmjRJUVFRmj59ulasWOF0XAAAYCDHC4wkTZ06VVOnTj3rdo/Ho6VLl2rp0qVnHZOYmKj169eHIh4AnJvi+NO/pqa4mwPAJ3AvJAAAYBwKDAAAMA4FBgAAGIcCAwAAjEOBAQAAxgnJWUgAYCLf9hpJUuynDwMQBpiBAQAAxqHAAAAA41BgAACAcTgGBkCfVVxcLEm6/gZ3cwDoOWZgAPQJpXMrVDq3wu0YABxCgQEAAMahwAAAAONQYAAAgHEoMAAAwDichQQAPcCBwEB4YAYGAAAYhwIDAACMQ4EBAADGocAAAADjUGAAAIBxKDAAAMA4FBgAAGAcCgwAGORw4RtuRwDCAgUGAAAYhwIDIKIdGD1GB0aPcTsGAIdRYAAgQqWvTXc7AhAyFBgAAGAcCgwAADAOBQYAABiHAgMAAIzT3+0AABAKXQewvuhyDgChwQwMAAAwDgUGAAAYhwIDAACMQ4EBgD6gdG6FSudWuB0DcAwFBgAAGIcCAwB90OHCN7izNYxGgQEAAMahwAAAAONQYAAAgHEoMAAc59teI9/2GrdjAIhgFBgAAGAcCgwAADAON3MEgD7kyRlTJUkzUu93OQlwYZiBAQAAxqHAADgvXf+TBwA3UGAAAIBxKDAAAMA4FBgAruDuyAAuBAUGAKDyijS3IwA9wmnUAGAATn8GgjEDAwAAjEOBAQAAxqHAAAAA41BgAACAcSgwAADAOBQYAABgnJAXmMcee0wej0fz58+31504cUL5+fkaNmyYLrroIk2fPl0NDQ1Bz6urq9OUKVM0aNAgJSUlaeHChTp16lSo4wKAMcor0rh+C/qskF4HZu/evXruuef0pS99KWj9vffeqy1btujXv/614uPjVVBQoK997Wv64x//KEnq6OjQlClT5PP5tGvXLv3jH//QnXfeqQEDBujRRx8NZWQAoVAc/9GvLe7mMBBXKwa6F7IZmOPHjys3N1c//vGPNXToUHt9S0uLfvrTn+qpp57STTfdpPHjx2v16tXatWuXdu/eLUnatm2b9u/fr1/+8pcaN26cbrnlFj300EMqLS1Ve3t7qCIDOE/FxcUqLi52OwYukG97jXzba9yOAZyTkBWY/Px8TZkyRdnZ2UHrq6urdfLkyaD1o0ePVkpKiiorKyVJlZWVSk9Pl9frtcfk5OQoEAiotrY2VJEBAIAhQvIR0gsvvKC33npLe/fu/cQ2v9+v6OhoJSQkBK33er3y+/32mP8uL13bu7Z1p62tTW1tbfbjQCBwIbsAwFRdH1elpribA0BIOV5g6uvr9f3vf19lZWWKjY11+uXPqqSkRA8++GCvvR8ARIKuj/6uv8HdHEBPOf4RUnV1tRobG/XlL39Z/fv3V//+/bVjxw6tWLFC/fv3l9frVXt7u5qbm4Oe19DQIJ/PJ0ny+XyfOCup63HXmDMVFRWppaXFXurr653eNaBPSl+brvS16W7H+EyjCrdoVOEWt2MA6CWOF5hJkyZp3759qqmpsZeMjAzl5ubaXw8YMEDl5eX2cw4ePKi6ujplZWVJkrKysrRv3z41NjbaY8rKyhQXF6exY8d2+74xMTGKi4sLWgAAQGRy/COkIUOG6PLLLw9aN3jwYA0bNsxeP2vWLC1YsECJiYmKi4vTPffco6ysLF199dWSpMmTJ2vs2LG64447tGzZMvn9fj3wwAPKz89XTEyM05EBILJwHBD6gJBeB+Zsnn76aUVFRWn69Olqa2tTTk6OnnnmGXt7v379tHnzZs2bN09ZWVkaPHiw8vLytHTpUjfiAgCAMNMrBeb1118PehwbG6vS0lKVlpae9TkjR47Uq6++GuJkABAmuNgf0CPcCwkAABjHlY+QAADO6zoL64Peu4IF4BpmYAAggh0YPUYHRo9xOwbgOAoMAAAwDgUGAAAYhwIDAACMQ4EBAADG4SwkADAMN2AEmIEBAAAGosAAAADjUGAA9ClPzpjqdgQADqDAADgnXBANQDihwAAAAONQYAAAgHEoMAAAwDgUGAAAYBwKDAAAMA4FBgAAGIcCAwAAjMO9kAD0OYcL3zj9Ray7OQCcP2ZgAISFw4VvfFwsAOAzMAMDIGRGFW6RJH3ATAcAhzEDAwAAjEOBAQAAxqHAAOhV3BQSgBMoMAAQRtLXpit9bbrbMYCwR4EBAADGocAAAADjUGAAAIBxKDAAAMA4FBggDHAVWgDoGQoMAAAwDgUGAAAYhwIDAACMw80cATimvCLt9Bee37obBEDEo8AAcNWTM6ZKkmak3u9yEgAm4SMkAABgHAoMAAAwDgUGQFgpLi5WcXGx2zEAhDkKDAAAMA4H8QIIMqpwiyTpg8emuJwE58q3vUaSFOtuDKBXUWAAnDf79gf85DxvdmHk9xDoET5CAgAAxmEGBkCPlM6t6JX3Ka9I06Sb3u+V9wJgHgoMgO4Vx5/+NTXF3RwwyoHRYyRJY9494HISRDo+QgIAAMahwAAAAONQYAAAgHEoMAAAwDgUGAAAYBwKDBAiowq32BcpAwA4iwIDAACMQ4EBAJy/4viPrxkE9CIuZAcA6DHu4QS3MQMDAACMQ4EBAADGocAAAFzh214j3/Yat2PAUBQYAGGLH3AAzsbxAlNSUqKrrrpKQ4YMUVJSkqZNm6aDBw8GjTlx4oTy8/M1bNgwXXTRRZo+fboaGhqCxtTV1WnKlCkaNGiQkpKStHDhQp06dcrpuAAAwECOF5gdO3YoPz9fu3fvVllZmU6ePKnJkyertbXVHnPvvffqlVde0a9//Wvt2LFDR48e1de+9jV7e0dHh6ZMmaL29nbt2rVLa9eu1Zo1a7R48WKn4wLoRelr092OACBCOH4a9datW4Mer1mzRklJSaqurtYNN9yglpYW/fSnP9X69et10003SZJWr16tMWPGaPfu3br66qu1bds27d+/X7///e/l9Xo1btw4PfTQQ7r//vtVXFys6Ohop2MDAACDhPwYmJaWFklSYmKiJKm6ulonT55Udna2PWb06NFKSUlRZWWlJKmyslLp6enyer32mJycHAUCAdXW1nb7Pm1tbQoEAkELAACITCEtMJ2dnZo/f76uvfZaXX755ZIkv9+v6OhoJSQkBI31er3y+/32mP8uL13bu7Z1p6SkRPHx8fYyYsQIh/cGAACEi5AWmPz8fL3zzjt64YUXQvk2kqSioiK1tLTYS319fcjfEzgnXGodABwXslsJFBQUaPPmzdq5c6cuueQSe73P51N7e7uam5uDZmEaGhrk8/nsMXv27Al6va6zlLrGnCkmJkYxMTEO7wUA4EI8OWOqJOl/Nmx2OQkijeMzMJZlqaCgQBs3blRFRYVSU1ODto8fP14DBgxQeXm5ve7gwYOqq6tTVlaWJCkrK0v79u1TY2OjPaasrExxcXEaO3as05EBAIBhHJ+Byc/P1/r167Vp0yYNGTLEPmYlPj5eAwcOVHx8vGbNmqUFCxYoMTFRcXFxuueee5SVlaWrr75akjR58mSNHTtWd9xxh5YtWya/368HHnhA+fn5zLIAQBjqOkX+RZdzoO9wvMA8++yzkqQbb7wxaP3q1av17W9/W5L09NNPKyoqStOnT1dbW5tycnL0zDPP2GP79eunzZs3a968ecrKytLgwYOVl5enpUuXOh0XAAAYyPECY1nWZ46JjY1VaWmpSktLzzpm5MiRevXVV52MBgAAIgT3QgIAAMahwAAAAONQYAAAgHEoMACAkDtc+IbbERBhKDAAAMA4FBgACEMHRo/RgdFj3I4BhC0KDAAAMA4FBgAAGCdkN3MEAPRdpXMr3I6ACMcMDAAAMA4FBgAAGIcCA/Qyzi4BgAtHgQEAAMahwAAAAONQYAAAgHEoMEAYKS4uVnFxsdsxACDsUWAAA4wq3KJRhVvcjgH0utK5FY5eU4Z/S5GDAgMACA/F8acX4BxQYIAwVF6RpvKKNLdjAEDY4lYCAABXdX2k80Hsx+vsayXdWOpCIpiAGRgAAGAcCgwAIKykr013OwIMQIEBAPQKLhMAJ1FgAAA4BxxcH14oMAAAwDgUGAAAYBwKDAAAMA4FBgAAGIcCAwDo8w6MHvPxxfNgBK7EC/SSrmtbvOhyDgCIBMzAwFj8jwkA+i4KDOCyJ2dMdTsCABiHj5AAl5TOrfjMMb7tNZKk2E8fBgB9DjMwAAB8pHRuxTn95wLuo8AAhuIYIAB9GQUGMElx/OmlG0/OmMrxNMC5+pR/SzADBQYA0Gelr023L3HQncOFb/RiGvQEBQYAABiHAgMACHt8RIozUWAAAIBxKDAAAMA4FBgAAGAcCgwAwBiHC9/gzCBIosAARvq00z4BoC+gwCDsjSrcolGFW0Ly2hQBAN3hrKfwR4GBzfR7gPDN5jSm2AFnFRcXq7i42O0YOAN3o+5DumYxPnhsistJnGVy6QL6ovKKtNNfeH7rbhAYjRkYAABgHAoMAAAwDgUG5uDusQA+wnEpoMA44LPuZgr3lFekffx5OwAgYnAQb1/UNYtR3OJuDjiCg5gB9EXMwAAA0IeE8tpavYkZGBin6+O6Fy/kRbpmoVJTLjhPuOo6PoDjBBDJyivSNOmm992OEXL2ZTBiv3l6BTPoFBgAAHrCt71GkuSfOM61DPZ/5EpOSZLGvHtA0scX9PyfDZvdCdaL+AgJfYJve439TedsTL8SMQCX9OAMyd48eyrSz9RiBgZ9ysfTsC4HAQBcEGZgAACAccK6wJSWlmrUqFGKjY1VZmam9uzZ43YkAAAkRc7ZPKYK2wKzYcMGLViwQEuWLNFbb72lK664Qjk5OWpsbHQ7GgAAcFnYFpinnnpKs2fP1l133aWxY8dq1apVGjRokH72s5+5HQ0AALgsLA/ibW9vV3V1tYqKiux1UVFRys7OVmVlZbfPaWtrU1tbm/24peX0OfKBQCC0YSV1/F9Hr73Xhehs+48kKeCxTq84I+//tbd+tDq89uPM3F2/38c7Tv/albvt5MlPZG9t7Tz9Gp7jZ32truc4vf89yX2s7aOvPW3nnLu715H0idfq6f6ES+7W1k77dc5lH/pC7q73I3dw7p78HQ9l7jO/p3an6+eU0/8uu17vxEe5A4HAWd/Lfq0w+17fpSuXZVmfPtAKQ0eOHLEkWbt27Qpav3DhQmvChAndPmfJkiWWJBYWFhYWFpYIWOrr6z+1K4TlDMz5KCoq0oIFC+zHnZ2dampq0rBhw+TxeFxM5oxAIKARI0aovr5ecXFxbsdxHPtnNvbPbOyf2SJt/yzL0rFjx5ScnPyp48KywHzuc59Tv3791NDQELS+oaFBPp+v2+fExMQoJiYmaF1CQkKoIromLi4uIv6Cng37Zzb2z2zsn9kiaf/i4+M/c0xYHsQbHR2t8ePHq7y83F7X2dmp8vJyZWVluZgMAACEg7CcgZGkBQsWKC8vTxkZGZowYYKWL1+u1tZW3XXXXW5HAwAALgvbAjNjxgx9+OGHWrx4sfx+v8aNG6etW7fK6/W6Hc0VMTExWrJkySc+JosU7J/Z2D+zsX9mi/T9OxuPZX3WeUoAAADhJSyPgQEAAPg0FBgAAGAcCgwAADAOBQYAABiHAmOwtrY2jRs3Th6PRzU1NW7HccxXv/pVpaSkKDY2VsOHD9cdd9yho0ePuh3LER988IFmzZql1NRUDRw4UGlpaVqyZIna29vdjuaYRx55RNdcc40GDRoUMReTLC0t1ahRoxQbG6vMzEzt2bPH7UiO2Llzp2699VYlJyfL4/HopZdecjuSo0pKSnTVVVdpyJAhSkpK0rRp03Tw4EG3Yznm2Wef1Ze+9CX7AnZZWVl67bXX3I7VaygwBrvvvvs+81LLJpo4caJefPFFHTx4UL/97W/1/vvv6+tf/7rbsRzx7rvvqrOzU88995xqa2v19NNPa9WqVfrf//1ft6M5pr29XbfffrvmzZvndhRHbNiwQQsWLNCSJUv01ltv6YorrlBOTo4aGxvdjnbBWltbdcUVV6i0tNTtKCGxY8cO5efna/fu3SorK9PJkyc1efJktba2uh3NEZdccokee+wxVVdX680339RNN92k2267TbW1tW5H6x3O3H4Rve3VV1+1Ro8ebdXW1lqSrLffftvtSCGzadMmy+PxWO3t7W5HCYlly5ZZqampbsdw3OrVq634+Hi3Y1ywCRMmWPn5+fbjjo4OKzk52SopKXExlfMkWRs3bnQ7Rkg1NjZakqwdO3a4HSVkhg4dav3kJz9xO0avYAbGQA0NDZo9e7Z+8YtfaNCgQW7HCammpiatW7dO11xzjQYMGOB2nJBoaWlRYmKi2zHQjfb2dlVXVys7O9teFxUVpezsbFVWVrqYDOejpaVFkiLy31tHR4deeOEFtba29plb7lBgDGNZlr797W9r7ty5ysjIcDtOyNx///0aPHiwhg0bprq6Om3atMntSCHx17/+VStXrtTdd9/tdhR045///Kc6Ojo+cQVwr9crv9/vUiqcj87OTs2fP1/XXnutLr/8crfjOGbfvn266KKLFBMTo7lz52rjxo0aO3as27F6BQUmTBQWFsrj8Xzq8u6772rlypU6duyYioqK3I7cI+e6f10WLlyot99+W9u2bVO/fv105513ygrji0b3dP8k6ciRI7r55pt1++23a/bs2S4lPzfns39AOMnPz9c777yjF154we0ojrrssstUU1OjqqoqzZs3T3l5edq/f7/bsXoFtxIIEx9++KH+9a9/feqYz3/+8/rGN76hV155RR6Px17f0dGhfv36KTc3V2vXrg111PNyrvsXHR39ifWHDx/WiBEjtGvXrrCdGu3p/h09elQ33nijrr76aq1Zs0ZRUeH9f4nz+fNbs2aN5s+fr+bm5hCnC5329nYNGjRIv/nNbzRt2jR7fV5enpqbmyNqZtDj8Wjjxo1B+xkpCgoKtGnTJu3cuVOpqaluxwmp7OxspaWl6bnnnnM7SsiF7c0c+5qLL75YF1988WeOW7FihR5++GH78dGjR5WTk6MNGzYoMzMzlBEvyLnuX3c6OzslnT5tPFz1ZP+OHDmiiRMnavz48Vq9enXYlxfpwv78TBYdHa3x48ervLzc/sHe2dmp8vJyFRQUuBsOn8myLN1zzz3auHGjXn/99YgvL9Lpv5/h/L3SSRQYw6SkpAQ9vuiiiyRJaWlpuuSSS9yI5Kiqqirt3btX1113nYYOHar3339fixYtUlpaWtjOvvTEkSNHdOONN2rkyJF64okn9OGHH9rbfD6fi8mcU1dXp6amJtXV1amjo8O+RtEXvvAF+++rSRYsWKC8vDxlZGRowoQJWr58uVpbW3XXXXe5He2CHT9+XH/961/tx4cOHVJNTY0SExM/8b3GRPn5+Vq/fr02bdqkIUOG2MctxcfHa+DAgS6nu3BFRUW65ZZblJKSomPHjmn9+vV6/fXX9bvf/c7taL3D1XOgcMEOHToUUadR//nPf7YmTpxoJSYmWjExMdaoUaOsuXPnWocPH3Y7miNWr15tSep2iRR5eXnd7t/27dvdjnbeVq5caaWkpFjR0dHWhAkTrN27d7sdyRHbt2/v9s8qLy/P7WiOONu/tdWrV7sdzRHf+c53rJEjR1rR0dHWxRdfbE2aNMnatm2b27F6DcfAAAAA44T/h+8AAABnoMAAAADjUGAAAIBxKDAAAMA4FBgAAGAcCgwAADAOBQYAABiHAgMAAIxDgQEAAMahwAAAAONQYAAAgHEoMAAAwDj/D+69Ahi8NJzeAAAAAElFTkSuQmCC\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.linear_model import LogisticRegression\n",
        "lr_model=LogisticRegression()\n",
        "lr_model_fit=lr_model.fit(pca_fit_pt,le_y_train)\n",
        "lr_pred=lr_model.predict(pca_transform)\n",
        "from sklearn.metrics import accuracy_score\n",
        "accuracy_score(lr_pred,le_y_test)\n",
        "from sklearn.linear_model import SGDClassifier\n",
        "sgd=SGDClassifier(loss=\"log_loss\",penalty=\"l2\",max_iter=100,learning_rate=\"optimal\")\n",
        "sgd_fit=sgd.fit(pca_fit_pt,le_y_train)\n",
        "sgd_pred=sgd.predict(pca_transform)\n",
        "from sklearn.metrics import accuracy_score\n",
        "accuracy_score(sgd_pred,le_y_test)\n",
        "from sklearn.metrics import classification_report\n",
        "classification_report(sgd_pred,le_y_test)\n",
        "from sklearn.metrics import confusion_matrix\n",
        "confusion_matrix(sgd_pred,le_y_test)\n",
        "from sklearn.metrics import f1_score\n",
        "f1_score(sgd_pred,le_y_test,average=\"weighted\")\n",
        "from sklearn.metrics import roc_auc_score\n",
        "roc_auc_score(sgd_pred,le_y_test)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Jf324oBwBs8U",
        "outputId": "c9927db1-663c-4a6f-941f-edf6738f7f15"
      },
      "execution_count": 101,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "np.float64(0.999062757719562)"
            ]
          },
          "metadata": {},
          "execution_count": 101
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "erca3af7D6h8"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}